### ISSUE TITLE
naming?

### ISSUE THREAD

**Issue by vm** [utkarshkukreti/select.rs#5]
Would it make more sense to call this repo something else? search for rust select on google will probably always find the select! macro, and it's not super clear what select.rs means. What do you think?

Thanks for your work!

**Comment by vm** [comment]
Side note: I'd love to help out by making writing documentation. I could get started this weekend if you'd like!

**Comment by utkarshkukreti** [comment]
I don't know about the name.. I chose it because I had (and have) no intention to allow modifying the tree; only to "select" data. I think if more people use/blog about the library, it could rank on the first page of Google for "select rust".

I'd really appreciate documentation pull requests. Please go ahead! :)
