### ISSUE TITLE
when I use this lib in my project, it cause "mismatched types" error

### ISSUE THREAD

**Issue by ucando** [utkarshkukreti/select.rs#8]
I try to use this lib in my project and I add it to my Cargo.toml like this:
```
[dependencies]
select = "*"
```
I follow the example, but it cause "mismatched types" error:
```
expected `select::document::Document`,
    found `&'static str`
(expected struct `select::document::Document`,
    found &-ptr) [E0308]
src/main.rs:16         let doc = Document::from(include_str!("index.html"));
```

then I clone this project from github, and try to run the example, it can run. what's the problem?

**Comment by utkarshkukreti** [comment]
Sorry about that. The example in the README was for the next version of the library which I had been meaning to publish for a while now. I just published it. Try running `cargo update -p select` and everything should work.

Also, I recommend specifying a version of the library like `select = "0.3.0"` so that any future breaking changes don't break your project.

**Comment by ucando** [comment]
thanks for your reply and the recommendation! it solved my problem
